# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
    config.vm.box = "lucid32"
    config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
    config.vm.network :bridged
    config.vm.share_folder "app", "/home/vagrant/app", "../"
    # allow for symlinks in the app folder
    config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app", "1"]
    config.vm.forward_port 8080, 8080
    config.vm.forward_port 5984, 5984
    #config.vm.provision :shell, :path => "scripts/provision.sh"
    config.vm.provision :chef_solo do |chef|
        chef.roles_path = "./roles"
        chef.add_role("db")
        chef.add_role("mq")
        chef.add_role("server")
    end
end
#http://www.opscode.com/blog/wp-content/uploads/2012/02/automate-all-the-things.png